### ISSUE TITLE
Emit events in setter functions

### ISSUE THREAD

**Issue by manboy-eth** [gnosis/zodiac-module-reality#75]
In the currently deployed version, it's hard for off-chain systems (analytics, UI, etc.) to keep track of changes to a Reality Module's parameters.

This could be solved by emitting events on setter functions:

- [ ] https://github.com/gnosis/zodiac-module-reality/blob/d05a496789079b60125a24f386d1a152e1479f4f/contracts/RealityModule.sol#L138
- [ ] https://github.com/gnosis/zodiac-module-reality/blob/d05a496789079b60125a24f386d1a152e1479f4f/contracts/RealityModule.sol#L147
- [ ] https://github.com/gnosis/zodiac-module-reality/blob/d05a496789079b60125a24f386d1a152e1479f4f/contracts/RealityModule.sol#L161
- [ ] https://github.com/gnosis/zodiac-module-reality/blob/d05a496789079b60125a24f386d1a152e1479f4f/contracts/RealityModule.sol#L172
- [ ] https://github.com/gnosis/zodiac-module-reality/blob/d05a496789079b60125a24f386d1a152e1479f4f/contracts/RealityModule.sol#L179
- [ ] https://github.com/gnosis/zodiac-module-reality/blob/d05a496789079b60125a24f386d1a152e1479f4f/contracts/RealityModule.sol#L187
- [ ]

**Comment by auryn-macmillan** [comment]
Yeah, I think this is valid.
I also think that we could add these events without invalidating the previous audits.
Thoughts, @nginnever ?
